name: underthesea.treebank
channels:
- defaults
dependencies:
- boto=2.46.1=py27_0
- bz2file=0.98=py27_0
- gensim=1.0.1=np112py27_0
- mkl=2017.0.1=0
- numpy=1.12.1=py27_0
- pip=9.0.1=py27_1
- python=2.7.11=5
- requests=2.13.0=py27_0
- scipy=0.19.0=np112py27_0
- six=1.10.0=py27_0
- smart_open=1.5.2=py27_0
- wheel=0.29.0=py27_0
- pip:
  - markupsafe==1.0
  - pandas==0.20.2
  - python-crfsuite==0.9.1
  - python-dateutil==2.6.0
  - pytz==2017.2
  - smart-open==1.5.2
  - tabulate==0.7.7
  - underscore.py==0.1.6
  - underthesea==1.1.0
  - xlrd==1.0.0
